### ISSUE TITLE
Bootable Media

### ISSUE THREAD

**Issue by hbotzombie** [LairdCP/Summit-SOM-Release-Packages#1]
Hi,

I am following the guide to get this installed on my DVK but when trying to get the image on to an SD Card via Balena Etcher it flags up an error saying the image is not bootable as it is missing the partition table. If I ignore and continue with it the process I get no log ins on the terminal program which indicates the image did not get installed correctly. Can somebody please help?

**Comment by john-nosky** [comment]
Hi hbotzombie,

Apologies, we do not provide support via GitHub comments, please submit a direct support ticket via the following link:

https://www.lairdconnect.com/resources/support
